[variables]
required = [
    "service_name",
    "username",
    "timestamp",
    "local_jar_path",
    "local_jar_basename"
]

[variables.defined]
remote_service_script_path = "/usr/local/bin/{service_name}.sh"
remote_deploy_path = "/usr/local/{service_name}/{service_name}.jar"
backup_path = "/u01/backup/{service_name}/{service_name}-{timestamp}.jar"
remote_base_path = "/home/{username}"

[[steps]]
type = "SftpCopy"
description = "Copying new deploy file to server"
source_path = "{local_jar_path}"
destination_path = "{remote_base_path}/{local_jar_basename}"
error_message = "Failed to copy new deploy file to server."

[[steps]]
type = "RemoteSudo"
description = "Stopping the service on remote server"
command = "{remote_service_script_path} stop"
error_message = "Failed to stop the service on the remote server."

[[steps]]
type = "RemoteSudo"
description = "Creating backup of current deployment"
command = "cp -a {remote_deploy_path} {backup_path}"
error_message = "Failed to create backup of the current deployment."

[[steps.rollback]]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[[steps]]
type = "RemoteSudo"
description = "Removing current deployment"
command = "rm {remote_deploy_path} -f"
error_message = "Failed to remove the current deployment."

[[steps.rollback]]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[[steps]]
type = "RemoteSudo"
description = "Deploying the new file"
command = "mv {remote_base_path}/{local_jar_basename} {remote_deploy_path}"
error_message = "Failed to deploy the new file."

[[steps.rollback]]
type = "RemoteSudo"
description = "Restoring backup of current deployment"
command = "cp -a {backup_path} {remote_deploy_path}"
error_message = "Failed to restore backup of the current deployment."

[[steps.rollback]]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[[steps]]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."

[[steps.rollback]]
type = "RemoteSudo"
description = "Restoring backup of current deployment"
command = "cp -a {backup_path} {remote_deploy_path}"
error_message = "Failed to restore backup of the current deployment."

[[steps.rollback]]
type = "RemoteSudo"
description = "Starting the service on remote server"
command = "{remote_service_script_path} start"
error_message = "Failed to start the service on the remote server."
