[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "deploy-rs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
scenario-rs = { package = "scenario-rs", path = "../scenario-rs" }
colored = "2.1.0"
chrono = "0.4.38"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
indicatif = "0.17.8"
