[package]
name = "cli"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "deploy-rs"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.15", features = ["derive"] }
deploy-rs-core = { package = "core", path = "../core" }
colored = "2.1.0"
chrono = "0.4.38"
anyhow = "1.0.86"
tracing = "0.1.40"
tracing-subscriber = "0.3.18"
tracing-core = "0.1.32"
