[package]
name = "gui"
version = "0.1.0"
description = "Rust SSH automation tool"
authors = ["st4s1k"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
tauri-build = { version = "1", features = [] }

[dependencies]
tauri = { version = "1", features = [ "window-maximize", "window-minimize", "window-close", "window-show", "window-unmaximize", "window-unminimize", "window-hide", "window-start-dragging", "dialog-all", "shell-open"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
scenario-rs = { package = "core", path = "../../core" }

[features]
# This feature is used for production builds or when a dev server is not specified, DO NOT REMOVE!!
custom-protocol = ["tauri/custom-protocol"]
