[package]
name = "scenario-rs"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "1.0.63"
regex = "1.10.6"
ssh2 = "0.9.4"
serde = { version = "1.0.207", features = ["derive"] }
serde_json = "1.0.124"
indicatif = "0.17.8"
chrono = "0.4.38"
